### PR TITLE
Extract viewbox coordinates for Nominatim search link

### PR DESCRIPTION
**Pull request by SrihariThalla**
Hi Arun,

The coordinates are not extracted properly from the GeoJSON `geometry` while passing to `nominatimLink`. Patched it up.

Thanks!

### CODE REVIEW

**Comment by planemad** [comment]
@SrihariThalla thanks for the patch!

We'll need to do some more digging into this, it fixes the link for multlinestring features, but for linestrings its still broken like `http://nominatim.openstreetmap.org/search.php?q=N%20Park%20Rd&polygon=1&bounded=1&viewbox=NaN%2CNaN%2CNaN%2CNaN`

Can you check if the link works for any single segment road name?

**Comment by SrihariThalla** [comment]
That breaks @planemad. I found a library for extracting coordinates in GeoJSON - [mapbox/geojson-coords](https://github.com/mapbox/geojson-coords).

Shall we use it as it would save us from reinventing the wheel? I hope it won't make the `bundle.js` heavy!

**Comment by SrihariThalla** [comment]
@planemad Can you check whether `bundle.js` is properly bundled?

BTW, not all features have `name`s! And the popups display 'undefined'. What shall we do about them? Shall we just not build the Nominatim search link at all for them?

**Comment by planemad** [comment]
👍 works great. Yes, features without name don't need a nominatim link

**Pull request merged**
